package org.corexero.indianmetrocore.graphs.topology.impl

import org.corexero.indianmetrocore.graphs.model.City
import org.corexero.indianmetrocore.graphs.model.GraphEdge
import org.corexero.indianmetrocore.graphs.model.LabelledGraphEdge
import org.corexero.indianmetrocore.graphs.model.SourceAndDestination


class DelhiCityTransitTopology : org.corexero.indianmetrocore.graphs.topology.CityTransitTopology {

    override val edges: List<GraphEdge>
        get() = listOf(
            GraphEdge("M-LXM", "M-NRM", 1),
            GraphEdge("M-NRM", "M-PTVR", 1),
            GraphEdge("M-PTVR", "M-KRKRD", 1),
            GraphEdge("M-KRKRD", "M-ANND", 1),
            GraphEdge("M-ANND", "M-KSH", 1),
            GraphEdge("M-KSH", "M-VSH", 1),
            GraphEdge("M-NDLC", "M-SCT", 1),
            GraphEdge("M-SCT", "M-SCTR", 1),
            GraphEdge("M-SCTR", "M-SCTR6", 1),
            GraphEdge("M-SCTR6", "M-SCTR5", 1),
            GraphEdge("M-SCTR5", "M-SCTR3", 1),
            GraphEdge("M-SCTR3", "M-NCC", 1),
            GraphEdge("M-NCC", "M-GLF", 1),
            GraphEdge("M-GLF", "M-BTN", 1),
            GraphEdge("M-BTN", "M-NDS", 1),
            GraphEdge("M-NDS", "M-NDSC", 1),
            GraphEdge("M-NDSC", "M-NDSCT", 1),
            GraphEdge("M-NDSCT", "M-NWS", 1),
            GraphEdge("M-NWS", "M-MYR", 1),
            GraphEdge("M-MYR", "M-MYRVHR", 1),
            GraphEdge("M-MYRVHR", "M-AKS", 1),
            GraphEdge("M-AKS", "M-YMN", 1),
            GraphEdge("M-YMN", "M-IND", 1),
            GraphEdge("M-IND", "M-SPR", 1),
            GraphEdge("M-SPR", "M-MDHS", 1),
            GraphEdge("M-MDHS", "M-BRK", 1),
            GraphEdge("M-BRK", "M-RJV", 1),
            GraphEdge("M-RJV", "M-RKS", 1),
            GraphEdge("M-RKS", "M-JHN", 1),
            GraphEdge("M-JHN", "M-KB", 1),
            GraphEdge("M-KB", "M-RJN", 1),
            GraphEdge("M-RJN", "M-PTL", 1),
            GraphEdge("M-PTL", "M-SHD", 1),
            GraphEdge("M-SHD", "M-KRT", 1),
            GraphEdge("M-KRT", "M-MTN", 1),
            GraphEdge("M-MTN", "M-RN", 1),
            GraphEdge("M-RN", "M-RJRG", 1),
            GraphEdge("M-RJRG", "M-TGR", 1),
            GraphEdge("M-TGR", "M-SBH", 1),
            GraphEdge("M-SBH", "M-TLK", 1),
            GraphEdge("M-TLK", "M-JNK", 1),
            GraphEdge("M-JNK", "M-JNKP", 1),
            GraphEdge("M-JNKP", "M-UTT", 1),
            GraphEdge("M-UTT", "M-UTTM", 1),
            GraphEdge("M-UTTM", "M-NWD", 1),
            GraphEdge("M-NWD", "M-DWR", 1),
            GraphEdge("M-DWR", "M-DWRK", 1),
            GraphEdge("M-DWRK", "M-DWRKS", 1),
            GraphEdge("M-DWRKS", "M-DWRKSC", 1),
            GraphEdge("M-DWRKSC", "M-DWRKSCT", 1),
            GraphEdge("M-DWRKSCT", "M-DWRKSCTR", 1),
            GraphEdge("M-DWRKSCTR", "M-DWRKSCTR1", 1),
            GraphEdge("M-DWRKSCTR1", "M-DWRKSCTR9", 1),
            GraphEdge("M-DWRKSCTR9", "M-DWRKSCTR8", 1),
            GraphEdge("M-DWRKSCTR8", "M-DWRKSCTR2", 1),
            GraphEdge("M-LXM", "M-YMN", 1),
            GraphEdge("M-MJPR", "M-JFR", 1),
            GraphEdge("M-JFR", "M-WLCM", 1),
            GraphEdge("M-WLCM", "M-EST", 1),
            GraphEdge("M-EST", "M-KRS", 1),
            GraphEdge("M-KRS", "M-KKDC", 1),
            GraphEdge("M-KKDC", "M-KRKRD", 1),
            GraphEdge("M-ANND", "M-IPE", 1),
            GraphEdge("M-IPE", "M-MNDW", 1),
            GraphEdge("M-MNDW", "M-ESTV", 1),
            GraphEdge("M-ESTV", "M-TRL", 1),
            GraphEdge("M-TRL", "M-MYRVH", 1),
            GraphEdge("M-MYRVH", "M-MYRVHR", 1),
            GraphEdge("M-MYRVHR", "M-HZR", 1),
            GraphEdge("M-HZR", "M-ASH", 1),
            GraphEdge("M-ASH", "M-VNB", 1),
            GraphEdge("M-VNB", "M-LJPT", 1),
            GraphEdge("M-LJPT", "M-SOEN", 1),
            GraphEdge("M-SOEN", "M-DLL", 1),
            GraphEdge("M-DLL", "M-SRJ", 1),
            GraphEdge("M-SRJ", "M-BHK", 1),
            GraphEdge("M-BHK", "M-SRM", 1),
            GraphEdge("M-SRM", "M-DRG", 1),
            GraphEdge("M-DRG", "M-DLH", 1),
            GraphEdge("M-DLH", "M-NAVR", 1),
            GraphEdge("M-NAVR", "M-MYP", 1),
            GraphEdge("M-MYP", "M-RJRG", 1),
            GraphEdge("M-RJRG", "M-ESB", 1),
            GraphEdge("M-ESB", "M-PNJBBG", 1),
            GraphEdge("M-PNJBBG", "M-SHK", 1),
            GraphEdge("M-SHK", "M-NTJ", 1),
            GraphEdge("M-NTJ", "M-SHL", 1),
            GraphEdge("M-SHL", "M-AZDP", 1),
            GraphEdge("M-AZDP", "M-MKPR", 1),
            GraphEdge("M-SHV", "M-JIEE", 1),
            GraphEdge("M-JIEE", "M-GKL", 1),
            GraphEdge("M-GKL", "M-MJPR", 1),
            GraphEdge("M-S55", "M-SCTR54", 1),
            GraphEdge("M-SCTR54", "M-SCTR53", 1),
            GraphEdge("M-SCTR53", "M-SCTR4", 1),
            GraphEdge("M-SCTR4", "M-PHS", 1),
            GraphEdge("M-PHS", "M-SKNDR", 1),
            GraphEdge("M-SKNDR", "M-DL2", 1),
            GraphEdge("M-DL2", "M-BLV", 1),
            GraphEdge("M-BLV", "M-CYB", 1),
            GraphEdge("M-CYB", "M-MLS", 1),
            GraphEdge("M-MLS", "M-PHS3Z", 1),
            GraphEdge("M-PHS3Z", "M-DL2", 1),
            GraphEdge("M-DWRK", "M-NNG", 1),
            GraphEdge("M-NNG", "M-NJF", 1),
            GraphEdge("M-NJF", "M-DHNS", 1),
            GraphEdge("M-RTH", "M-RHN", 1),
            GraphEdge("M-RHN", "M-RHNS", 1),
            GraphEdge("M-RHNS", "M-PTP", 1),
            GraphEdge("M-PTP", "M-KHT", 1),
            GraphEdge("M-KHT", "M-NTJ", 1),
            GraphEdge("M-NTJ", "M-KSHV", 1),
            GraphEdge("M-KSHV", "M-KNH", 1),
            GraphEdge("M-KNH", "M-INDR", 1),
            GraphEdge("M-INDR", "M-SHS", 1),
            GraphEdge("M-SHS", "M-PRTP", 1),
            GraphEdge("M-PRTP", "M-PLB", 1),
            GraphEdge("M-PLB", "M-TSH", 1),
            GraphEdge("M-TSH", "M-KSHM", 1),
            GraphEdge("M-KSHM", "M-SHST", 1),
            GraphEdge("M-SHST", "M-SLM", 1),
            GraphEdge("M-SLM", "M-WLCM", 1),
            GraphEdge("M-WLCM", "M-SHH", 1),
            GraphEdge("M-SHH", "M-MNS", 1),
            GraphEdge("M-MNS", "M-JHL", 1),
            GraphEdge("M-JHL", "M-DLS", 1),
            GraphEdge("M-DLS", "M-SHHD", 1),
            GraphEdge("M-SHHD", "M-RJB", 1),
            GraphEdge("M-RJB", "M-MJR", 1),
            GraphEdge("M-MJR", "M-SHY", 1),
            GraphEdge("M-SHY", "M-MHN", 1),
            GraphEdge("M-MHN", "M-ART", 1),
            GraphEdge("M-ART", "M-HND", 1),
            GraphEdge("M-HND", "M-SHHDS", 1),
            GraphEdge("M-NWDLH", "M-SHVJ", 1),
            GraphEdge("M-SHVJ", "M-DHL", 1),
            GraphEdge("M-DHL", "M-DACY", 1),
            GraphEdge("M-DACY", "M-APOT", 1),
            GraphEdge("M-APOT", "M-DWRKSCTR2", 1),
            GraphEdge("M-DWRKSCTR2", "M-IICCZ", 1),
            GraphEdge("M-KSHM", "M-LLQ", 1),
            GraphEdge("M-LLQ", "M-JAMD", 1),
            GraphEdge("M-JAMD", "M-DLHG", 1),
            GraphEdge("M-DLHG", "M-IT", 1),
            GraphEdge("M-IT", "M-MDHS", 1),
            GraphEdge("M-MDHS", "M-JNP", 1),
            GraphEdge("M-JNP", "M-CNTR", 1),
            GraphEdge("M-CNTR", "M-KHN", 1),
            GraphEdge("M-KHN", "M-JLN", 1),
            GraphEdge("M-JLN", "M-JNG", 1),
            GraphEdge("M-JNG", "M-LJPT", 1),
            GraphEdge("M-LJPT", "M-MLCD", 1),
            GraphEdge("M-MLCD", "M-KHCY", 1),
            GraphEdge("M-KHCY", "M-NHR", 1),
            GraphEdge("M-NHR", "M-KLK", 1),
            GraphEdge("M-KLK", "M-GVN", 1),
            GraphEdge("M-GVN", "M-HRK", 1),
            GraphEdge("M-HRK", "M-JSL", 1),
            GraphEdge("M-JSL", "M-SRT", 1),
            GraphEdge("M-SRT", "M-MHNS", 1),
            GraphEdge("M-MHNS", "M-TGH", 1),
            GraphEdge("M-TGH", "M-BDR", 1),
            GraphEdge("M-BDR", "M-SR", 1),
            GraphEdge("M-SR", "M-NHP", 1),
            GraphEdge("M-NHP", "M-MWL", 1),
            GraphEdge("M-MWL", "M-SCTR2", 1),
            GraphEdge("M-SCTR2", "M-BDK", 1),
            GraphEdge("M-BDK", "M-OLDF", 1),
            GraphEdge("M-OLDF", "M-NCAJ", 1),
            GraphEdge("M-NCAJ", "M-BTC", 1),
            GraphEdge("M-BTC", "M-ESC", 1),
            GraphEdge("M-ESC", "M-SNT", 1),
            GraphEdge("M-SNT", "M-RJNH", 1),
            GraphEdge("M-KRT", "M-SRSM", 1),
            GraphEdge("M-SRSM", "M-ASHK", 1),
            GraphEdge("M-ASHK", "M-PNJB", 1),
            GraphEdge("M-PNJB", "M-PNJBBG", 1),
            GraphEdge("M-PNJBBG", "M-SHVJP", 1),
            GraphEdge("M-SHVJP", "M-MDP", 1),
            GraphEdge("M-MDP", "M-PSC", 1),
            GraphEdge("M-PSC", "M-PSCH", 1),
            GraphEdge("M-PSCH", "M-PRG", 1),
            GraphEdge("M-PRG", "M-UDY", 1),
            GraphEdge("M-UDY", "M-MHR", 1),
            GraphEdge("M-MHR", "M-NNGL", 1),
            GraphEdge("M-NNGL", "M-NNGLR", 1),
            GraphEdge("M-NNGLR", "M-RJD", 1),
            GraphEdge("M-RJD", "M-MUDK", 1),
            GraphEdge("M-MUDK", "M-MNDKN", 1),
            GraphEdge("M-MNDKN", "M-GHV", 1),
            GraphEdge("M-GHV", "M-TKLM", 1),
            GraphEdge("M-TKLM", "M-TKRB", 1),
            GraphEdge("M-TKRB", "M-PNDT", 1),
            GraphEdge("M-PNDT", "M-BUSS", 1),
            GraphEdge("M-BUSS", "M-BRG", 1),
            GraphEdge("M-INDR", "M-ASHK", 1),
            GraphEdge("M-KRSHNP", "M-JNKP", 1),
            GraphEdge("M-JNKP", "M-DBR", 1),
            GraphEdge("M-DBR", "M-DSH", 1),
            GraphEdge("M-DSH", "M-PLM", 1),
            GraphEdge("M-PLM", "M-SDR", 1),
            GraphEdge("M-SDR", "M-TRM", 1),
            GraphEdge("M-TRM", "M-SHN", 1),
            GraphEdge("M-SHN", "M-VSN", 1),
            GraphEdge("M-VSN", "M-MNR", 1),
            GraphEdge("M-MNR", "M-RKP", 1),
            GraphEdge("M-RKP", "M-ITZ", 1),
            GraphEdge("M-ITZ", "M-HZK", 1),
            GraphEdge("M-HZK", "M-PNC", 1),
            GraphEdge("M-PNC", "M-CHR", 1),
            GraphEdge("M-CHR", "M-GRT", 1),
            GraphEdge("M-GRT", "M-NHRN", 1),
            GraphEdge("M-NHRN", "M-KLK", 1),
            GraphEdge("M-KLK", "M-OKH", 1),
            GraphEdge("M-OKH", "M-SKH", 1),
            GraphEdge("M-SKH", "M-JMML", 1),
            GraphEdge("M-JMML", "M-OKHL", 1),
            GraphEdge("M-OKHL", "M-JSLV", 1),
            GraphEdge("M-JSLV", "M-KLN", 1),
            GraphEdge("M-KLN", "M-OKHLB", 1),
            GraphEdge("M-OKHLB", "M-BTN", 1),
            GraphEdge("M-DPT", "M-GNDF", 1),
            GraphEdge("M-GNDF", "M-DLT", 1),
            GraphEdge("M-DLT", "M-ALP", 1),
            GraphEdge("M-ALP", "M-JYP", 1),
            GraphEdge("M-JYP", "M-KNW", 1),
            GraphEdge("M-KNW", "M-NDSCTR", 1),
            GraphEdge("M-NDSCTR", "M-SCTR1", 1),
            GraphEdge("M-SCTR1", "M-NDSCTR14", 1),
            GraphEdge("M-NDSCTR14", "M-NDSCTR145", 1),
            GraphEdge("M-NDSCTR145", "M-NDSCTR144", 1),
            GraphEdge("M-NDSCTR144", "M-NDSCTR143", 1),
            GraphEdge("M-NDSCTR143", "M-NDSCTR142", 1),
            GraphEdge("M-NDSCTR142", "M-NDSCTR13", 1),
            GraphEdge("M-NDSCTR13", "M-SCTR8", 1),
            GraphEdge("M-SCTR8", "M-NSZ", 1),
            GraphEdge("M-NSZ", "M-NDSCTR81", 1),
            GraphEdge("M-NDSCTR81", "M-NDSCTR10", 1),
            GraphEdge("M-NDSCTR10", "M-NDSCTR7", 1),
            GraphEdge("M-NDSCTR7", "M-NDSCTR5", 1),
            GraphEdge("M-NDSCTR5", "M-NDSCTR51", 1),
            GraphEdge("M-SMY", "M-RHNSC", 1),
            GraphEdge("M-RHNSC", "M-HDR", 1),
            GraphEdge("M-HDR", "M-JGPI", 1),
            GraphEdge("M-JGPI", "M-ADR", 1),
            GraphEdge("M-ADR", "M-AZDP", 1),
            GraphEdge("M-AZDP", "M-MDL", 1),
            GraphEdge("M-MDL", "M-GTB", 1),
            GraphEdge("M-GTB", "M-VSHW", 1),
            GraphEdge("M-VSHW", "M-VDH", 1),
            GraphEdge("M-VDH", "M-CVL", 1),
            GraphEdge("M-CVL", "M-KSHM", 1),
            GraphEdge("M-KSHM", "M-CHN", 1),
            GraphEdge("M-CHN", "M-CHW", 1),
            GraphEdge("M-CHW", "M-NWDLH", 1),
            GraphEdge("M-NWDLH", "M-RJV", 1),
            GraphEdge("M-RJV", "M-PTLC", 1),
            GraphEdge("M-PTLC", "M-CNTR", 1),
            GraphEdge("M-CNTR", "M-UDYG", 1),
            GraphEdge("M-UDYG", "M-LKK", 1),
            GraphEdge("M-LKK", "M-JRB", 1),
            GraphEdge("M-JRB", "M-DLL", 1),
            GraphEdge("M-DLL", "M-AMS", 1),
            GraphEdge("M-AMS", "M-GRN", 1),
            GraphEdge("M-GRN", "M-HZK", 1),
            GraphEdge("M-HZK", "M-MVNR", 1),
            GraphEdge("M-MVNR", "M-SAKT", 1),
            GraphEdge("M-SAKT", "M-QTB", 1),
            GraphEdge("M-QTB", "M-CHH", 1),
            GraphEdge("M-CHH", "M-SLT", 1),
            GraphEdge("M-SLT", "M-GHTR", 1),
            GraphEdge("M-GHTR", "M-ARJ", 1),
            GraphEdge("M-ARJ", "M-GRD", 1),
            GraphEdge("M-GRD", "M-SKNDR", 1),
            GraphEdge("M-SKNDR", "M-MGRD", 1),
            GraphEdge("M-MGRD", "M-IFF", 1),
            GraphEdge("M-IFF", "M-MLL", 1),
            GraphEdge("M-NDSCTR51", "M-SCTR5", 0)
        )

    override fun aliasesOf(stationCode: String): List<String> {
        val extra = aliasGroups()[stationCode].orEmpty()
        return listOf(stationCode) + extra
    }

    override fun edgeLineLabels(): Map<SourceAndDestination, List<LabelledGraphEdge>> {
        return mapOf(
            SourceAndDestination("M-VSH", "M-KSH") to listOf(LabelledGraphEdge("B4", 1)),
            SourceAndDestination("M-KSH", "M-VSH") to listOf(LabelledGraphEdge("B3", 1)),
            SourceAndDestination("M-KSH", "M-ANND") to listOf(LabelledGraphEdge("B4", 1)),
            SourceAndDestination("M-ANND", "M-KSH") to listOf(LabelledGraphEdge("B3", 1)),
            SourceAndDestination("M-ANND", "M-KRKRD") to listOf(LabelledGraphEdge("B4", 1)),
            SourceAndDestination("M-KRKRD", "M-ANND") to listOf(LabelledGraphEdge("B3", 1)),
            SourceAndDestination("M-KRKRD", "M-PTVR") to listOf(LabelledGraphEdge("B4", 1)),
            SourceAndDestination("M-PTVR", "M-KRKRD") to listOf(LabelledGraphEdge("B3", 1)),
            SourceAndDestination("M-PTVR", "M-NRM") to listOf(LabelledGraphEdge("B4", 1)),
            SourceAndDestination("M-NRM", "M-PTVR") to listOf(LabelledGraphEdge("B3", 1)),
            SourceAndDestination("M-NRM", "M-LXM") to listOf(LabelledGraphEdge("B4", 1)),
            SourceAndDestination("M-LXM", "M-NRM") to listOf(LabelledGraphEdge("B3", 1)),
            SourceAndDestination("M-LXM", "M-YMN") to listOf(LabelledGraphEdge("B4", 1)),
            SourceAndDestination("M-YMN", "M-LXM") to listOf(LabelledGraphEdge("B3", 1)),
            SourceAndDestination("M-NDLC", "M-SCT") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-SCT", "M-NDLC") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-SCT", "M-SCTR") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-SCTR", "M-SCT") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-SCTR", "M-SCTR6") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-SCTR6", "M-SCTR") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-SCTR6", "M-SCTR5") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-SCTR5", "M-SCTR6") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-SCTR5", "M-SCTR3") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-SCTR3", "M-SCTR5") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-SCTR3", "M-NCC") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-NCC", "M-SCTR3") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-NCC", "M-GLF") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-GLF", "M-NCC") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-GLF", "M-BTN") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-BTN", "M-GLF") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-BTN", "M-NDS") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-NDS", "M-BTN") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-NDS", "M-NDSC") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-NDSC", "M-NDS") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-NDSC", "M-NDSCT") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-NDSCT", "M-NDSC") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-NDSCT", "M-NWS") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-NWS", "M-NDSCT") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-NWS", "M-MYR") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-MYR", "M-NWS") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-MYR", "M-MYRVHR") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-MYRVHR", "M-MYR") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-MYRVHR", "M-AKS") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-AKS", "M-MYRVHR") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-AKS", "M-YMN") to listOf(LabelledGraphEdge("B2", 1)),
            SourceAndDestination("M-YMN", "M-AKS") to listOf(LabelledGraphEdge("B1", 1)),
            SourceAndDestination("M-YMN", "M-IND") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-IND", "M-YMN") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-IND", "M-SPR") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-SPR", "M-IND") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-SPR", "M-MDHS") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-MDHS", "M-SPR") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-MDHS", "M-BRK") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-BRK", "M-MDHS") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-BRK", "M-RJV") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-RJV", "M-BRK") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-RJV", "M-RKS") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-RKS", "M-RJV") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-RKS", "M-JHN") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-JHN", "M-RKS") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-JHN", "M-KB") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-KB", "M-JHN") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-KB", "M-RJN") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-RJN", "M-KB") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-RJN", "M-PTL") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-PTL", "M-RJN") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-PTL", "M-SHD") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-SHD", "M-PTL") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-SHD", "M-KRT") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-KRT", "M-SHD") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-KRT", "M-MTN") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-MTN", "M-KRT") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-MTN", "M-RN") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-RN", "M-MTN") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-RN", "M-RJRG") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-RJRG", "M-RN") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-RJRG", "M-TGR") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-TGR", "M-RJRG") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-TGR", "M-SBH") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-SBH", "M-TGR") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-SBH", "M-TLK") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-TLK", "M-SBH") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-TLK", "M-JNK") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-JNK", "M-TLK") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-JNK", "M-JNKP") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-JNKP", "M-JNK") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-JNKP", "M-UTT") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-UTT", "M-JNKP") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-UTT", "M-UTTM") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-UTTM", "M-UTT") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-UTTM", "M-NWD") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-NWD", "M-UTTM") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-NWD", "M-DWR") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-DWR", "M-NWD") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-DWR", "M-DWRK") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-DWRK", "M-DWR") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-DWRK", "M-DWRKS") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-DWRKS", "M-DWRK") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-DWRKS", "M-DWRKSC") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-DWRKSC", "M-DWRKS") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-DWRKSC", "M-DWRKSCT") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-DWRKSCT", "M-DWRKSC") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-DWRKSCT", "M-DWRKSCTR") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-DWRKSCTR", "M-DWRKSCT") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-DWRKSCTR", "M-DWRKSCTR1") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-DWRKSCTR1", "M-DWRKSCTR") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-DWRKSCTR1", "M-DWRKSCTR9") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-DWRKSCTR9", "M-DWRKSCTR1") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-DWRKSCTR9", "M-DWRKSCTR8") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-DWRKSCTR8", "M-DWRKSCTR9") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-DWRKSCTR8", "M-DWRKSCTR2") to listOf(
                LabelledGraphEdge("B2", 1),
                LabelledGraphEdge("B4", 1)
            ),
            SourceAndDestination("M-DWRKSCTR2", "M-DWRKSCTR8") to listOf(
                LabelledGraphEdge("B1", 1),
                LabelledGraphEdge("B3", 1)
            ),
            SourceAndDestination("M-MJPR", "M-JFR") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-JFR", "M-MJPR") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-JFR", "M-WLCM") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-WLCM", "M-JFR") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-WLCM", "M-EST") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-EST", "M-WLCM") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-EST", "M-KRS") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-KRS", "M-EST") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-KRS", "M-KKDC") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-KKDC", "M-KRS") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-KKDC", "M-KRKRD") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-KRKRD", "M-KKDC") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-ANND", "M-IPE") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-IPE", "M-ANND") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-IPE", "M-MNDW") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-MNDW", "M-IPE") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-MNDW", "M-ESTV") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-ESTV", "M-MNDW") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-ESTV", "M-TRL") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-TRL", "M-ESTV") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-TRL", "M-MYRVH") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-MYRVH", "M-TRL") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-MYRVH", "M-MYRVHR") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-MYRVHR", "M-MYRVH") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-MYRVHR", "M-HZR") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-HZR", "M-MYRVHR") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-HZR", "M-ASH") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-ASH", "M-HZR") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-ASH", "M-VNB") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-VNB", "M-ASH") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-VNB", "M-LJPT") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-LJPT", "M-VNB") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-LJPT", "M-SOEN") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-SOEN", "M-LJPT") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-SOEN", "M-DLL") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-DLL", "M-SOEN") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-DLL", "M-SRJ") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-SRJ", "M-DLL") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-SRJ", "M-BHK") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-BHK", "M-SRJ") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-BHK", "M-SRM") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-SRM", "M-BHK") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-SRM", "M-DRG") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-DRG", "M-SRM") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-DRG", "M-DLH") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-DLH", "M-DRG") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-DLH", "M-NAVR") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-NAVR", "M-DLH") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-NAVR", "M-MYP") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-MYP", "M-NAVR") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-MYP", "M-RJRG") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-RJRG", "M-MYP") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-RJRG", "M-ESB") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-ESB", "M-RJRG") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-ESB", "M-PNJBBG") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-PNJBBG", "M-ESB") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-PNJBBG", "M-SHK") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-SHK", "M-PNJBBG") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-SHK", "M-NTJ") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-NTJ", "M-SHK") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-NTJ", "M-SHL") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-SHL", "M-NTJ") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-SHL", "M-AZDP") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-AZDP", "M-SHL") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-AZDP", "M-MKPR") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-MKPR", "M-AZDP") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-SHV", "M-JIEE") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-JIEE", "M-SHV") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-JIEE", "M-GKL") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-GKL", "M-JIEE") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-GKL", "M-MJPR") to listOf(LabelledGraphEdge("P1", 1)),
            SourceAndDestination("M-MJPR", "M-GKL") to listOf(LabelledGraphEdge("P2", 1)),
            SourceAndDestination("M-S55", "M-SCTR54") to listOf(LabelledGraphEdge("RA1", 1)),
            SourceAndDestination("M-SCTR54", "M-S55") to listOf(LabelledGraphEdge("RA2", 1)),
            SourceAndDestination("M-SCTR54", "M-SCTR53") to listOf(LabelledGraphEdge("RA1", 1)),
            SourceAndDestination("M-SCTR53", "M-SCTR54") to listOf(LabelledGraphEdge("RA2", 1)),
            SourceAndDestination("M-SCTR53", "M-SCTR4") to listOf(LabelledGraphEdge("RA1", 1)),
            SourceAndDestination("M-SCTR4", "M-SCTR53") to listOf(LabelledGraphEdge("RA2", 1)),
            SourceAndDestination("M-SCTR4", "M-PHS") to listOf(LabelledGraphEdge("RA1", 1)),
            SourceAndDestination("M-PHS", "M-SCTR4") to listOf(LabelledGraphEdge("RA2", 1)),
            SourceAndDestination("M-PHS", "M-SKNDR") to listOf(LabelledGraphEdge("RA1", 1)),
            SourceAndDestination("M-SKNDR", "M-PHS") to listOf(LabelledGraphEdge("RA2", 1)),
            SourceAndDestination("M-SKNDR", "M-DL2") to listOf(LabelledGraphEdge("RA1", 1)),
            SourceAndDestination("M-DL2", "M-SKNDR") to listOf(LabelledGraphEdge("RA2", 1)),
            SourceAndDestination("M-DL2", "M-BLV") to listOf(LabelledGraphEdge("RA1", 1)),
            SourceAndDestination("M-BLV", "M-CYB") to listOf(LabelledGraphEdge("RA1", 1)),
            SourceAndDestination("M-CYB", "M-MLS") to listOf(LabelledGraphEdge("RA1", 1)),
            SourceAndDestination("M-MLS", "M-PHS3Z") to listOf(LabelledGraphEdge("RA1", 1)),
            SourceAndDestination("M-PHS3Z", "M-DL2") to listOf(LabelledGraphEdge("RA2", 1)),
            SourceAndDestination("M-DWRK", "M-NNG") to listOf(LabelledGraphEdge("GR1", 1)),
            SourceAndDestination("M-NNG", "M-DWRK") to listOf(LabelledGraphEdge("GR2", 1)),
            SourceAndDestination("M-NNG", "M-NJF") to listOf(LabelledGraphEdge("GR1", 1)),
            SourceAndDestination("M-NJF", "M-NNG") to listOf(LabelledGraphEdge("GR2", 1)),
            SourceAndDestination("M-NJF", "M-DHNS") to listOf(LabelledGraphEdge("GR1", 1)),
            SourceAndDestination("M-DHNS", "M-NJF") to listOf(LabelledGraphEdge("GR2", 1)),
            SourceAndDestination("M-RTH", "M-RHN") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-RHN", "M-RTH") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-RHN", "M-RHNS") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-RHNS", "M-RHN") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-RHNS", "M-PTP") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-PTP", "M-RHNS") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-PTP", "M-KHT") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-KHT", "M-PTP") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-KHT", "M-NTJ") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-NTJ", "M-KHT") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-NTJ", "M-KSHV") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-KSHV", "M-NTJ") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-KSHV", "M-KNH") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-KNH", "M-KSHV") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-KNH", "M-INDR") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-INDR", "M-KNH") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-INDR", "M-SHS") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-SHS", "M-INDR") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-SHS", "M-PRTP") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-PRTP", "M-SHS") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-PRTP", "M-PLB") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-PLB", "M-PRTP") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-PLB", "M-TSH") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-TSH", "M-PLB") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-TSH", "M-KSHM") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-KSHM", "M-TSH") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-KSHM", "M-SHST") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-SHST", "M-KSHM") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-SHST", "M-SLM") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-SLM", "M-SHST") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-SLM", "M-WLCM") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-WLCM", "M-SLM") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-WLCM", "M-SHH") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-SHH", "M-WLCM") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-SHH", "M-MNS") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-MNS", "M-SHH") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-MNS", "M-JHL") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-JHL", "M-MNS") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-JHL", "M-DLS") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-DLS", "M-JHL") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-DLS", "M-SHHD") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-SHHD", "M-DLS") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-SHHD", "M-RJB") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-RJB", "M-SHHD") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-RJB", "M-MJR") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-MJR", "M-RJB") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-MJR", "M-SHY") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-SHY", "M-MJR") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-SHY", "M-MHN") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-MHN", "M-SHY") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-MHN", "M-ART") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-ART", "M-MHN") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-ART", "M-HND") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-HND", "M-ART") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-HND", "M-SHHDS") to listOf(LabelledGraphEdge("R1", 1)),
            SourceAndDestination("M-SHHDS", "M-HND") to listOf(LabelledGraphEdge("R2", 1)),
            SourceAndDestination("M-NWDLH", "M-SHVJ") to listOf(LabelledGraphEdge("A1", 1)),
            SourceAndDestination("M-SHVJ", "M-NWDLH") to listOf(LabelledGraphEdge("A2", 1)),
            SourceAndDestination("M-SHVJ", "M-DHL") to listOf(LabelledGraphEdge("A1", 1)),
            SourceAndDestination("M-DHL", "M-SHVJ") to listOf(LabelledGraphEdge("A2", 1)),
            SourceAndDestination("M-DHL", "M-DACY") to listOf(LabelledGraphEdge("A1", 1)),
            SourceAndDestination("M-DACY", "M-DHL") to listOf(LabelledGraphEdge("A2", 1)),
            SourceAndDestination("M-DACY", "M-APOT") to listOf(LabelledGraphEdge("A1", 1)),
            SourceAndDestination("M-APOT", "M-DACY") to listOf(LabelledGraphEdge("A2", 1)),
            SourceAndDestination("M-APOT", "M-DWRKSCTR2") to listOf(LabelledGraphEdge("A1", 1)),
            SourceAndDestination("M-DWRKSCTR2", "M-APOT") to listOf(LabelledGraphEdge("A2", 1)),
            SourceAndDestination("M-DWRKSCTR2", "M-IICCZ") to listOf(LabelledGraphEdge("A1", 1)),
            SourceAndDestination("M-IICCZ", "M-DWRKSCTR2") to listOf(LabelledGraphEdge("A2", 1)),
            SourceAndDestination("M-KSHM", "M-LLQ") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-LLQ", "M-KSHM") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-LLQ", "M-JAMD") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-JAMD", "M-LLQ") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-JAMD", "M-DLHG") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-DLHG", "M-JAMD") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-DLHG", "M-IT") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-IT", "M-DLHG") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-IT", "M-MDHS") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-MDHS", "M-IT") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-MDHS", "M-JNP") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-JNP", "M-MDHS") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-JNP", "M-CNTR") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-CNTR", "M-JNP") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-CNTR", "M-KHN") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-KHN", "M-CNTR") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-KHN", "M-JLN") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-JLN", "M-KHN") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-JLN", "M-JNG") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-JNG", "M-JLN") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-JNG", "M-LJPT") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-LJPT", "M-JNG") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-LJPT", "M-MLCD") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-MLCD", "M-LJPT") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-MLCD", "M-KHCY") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-KHCY", "M-MLCD") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-KHCY", "M-NHR") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-NHR", "M-KHCY") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-NHR", "M-KLK") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-KLK", "M-NHR") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-KLK", "M-GVN") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-GVN", "M-KLK") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-GVN", "M-HRK") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-HRK", "M-GVN") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-HRK", "M-JSL") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-JSL", "M-HRK") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-JSL", "M-SRT") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-SRT", "M-JSL") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-SRT", "M-MHNS") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-MHNS", "M-SRT") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-MHNS", "M-TGH") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-TGH", "M-MHNS") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-TGH", "M-BDR") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-BDR", "M-TGH") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-BDR", "M-SR") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-SR", "M-BDR") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-SR", "M-NHP") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-NHP", "M-SR") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-NHP", "M-MWL") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-MWL", "M-NHP") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-MWL", "M-SCTR2") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-SCTR2", "M-MWL") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-SCTR2", "M-BDK") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-BDK", "M-SCTR2") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-BDK", "M-OLDF") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-OLDF", "M-BDK") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-OLDF", "M-NCAJ") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-NCAJ", "M-OLDF") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-NCAJ", "M-BTC") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-BTC", "M-NCAJ") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-BTC", "M-ESC") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-ESC", "M-BTC") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-ESC", "M-SNT") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-SNT", "M-ESC") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-SNT", "M-RJNH") to listOf(LabelledGraphEdge("V1", 1)),
            SourceAndDestination("M-RJNH", "M-SNT") to listOf(LabelledGraphEdge("V2", 1)),
            SourceAndDestination("M-BRG", "M-BUSS") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-BUSS", "M-BRG") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-BUSS", "M-PNDT") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-PNDT", "M-BUSS") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-PNDT", "M-TKRB") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-TKRB", "M-PNDT") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-TKRB", "M-TKLM") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-TKLM", "M-TKRB") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-TKLM", "M-GHV") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-GHV", "M-TKLM") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-GHV", "M-MNDKN") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-MNDKN", "M-GHV") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-MNDKN", "M-MUDK") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-MUDK", "M-MNDKN") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-MUDK", "M-RJD") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-RJD", "M-MUDK") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-RJD", "M-NNGLR") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-NNGLR", "M-RJD") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-NNGLR", "M-NNGL") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-NNGL", "M-NNGLR") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-NNGL", "M-MHR") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-MHR", "M-NNGL") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-MHR", "M-UDY") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-UDY", "M-MHR") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-UDY", "M-PRG") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-PRG", "M-UDY") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-PRG", "M-PSCH") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-PSCH", "M-PRG") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-PSCH", "M-PSC") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-PSC", "M-PSCH") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-PSC", "M-MDP") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-MDP", "M-PSC") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-MDP", "M-SHVJP") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-SHVJP", "M-MDP") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-SHVJP", "M-PNJBBG") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-PNJBBG", "M-SHVJP") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-PNJBBG", "M-PNJB") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-PNJB", "M-PNJBBG") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-PNJB", "M-ASHK") to listOf(
                LabelledGraphEdge("G1", 1),
                LabelledGraphEdge("G3", 1)
            ),
            SourceAndDestination("M-ASHK", "M-PNJB") to listOf(
                LabelledGraphEdge("G2", 1),
                LabelledGraphEdge("G4", 1)
            ),
            SourceAndDestination("M-ASHK", "M-INDR") to listOf(LabelledGraphEdge("G1", 1)),
            SourceAndDestination("M-INDR", "M-ASHK") to listOf(LabelledGraphEdge("G2", 1)),
            SourceAndDestination("M-ASHK", "M-SRSM") to listOf(LabelledGraphEdge("G3", 1)),
            SourceAndDestination("M-SRSM", "M-ASHK") to listOf(LabelledGraphEdge("G4", 1)),
            SourceAndDestination("M-SRSM", "M-KRT") to listOf(LabelledGraphEdge("G3", 1)),
            SourceAndDestination("M-KRT", "M-SRSM") to listOf(LabelledGraphEdge("G4", 1)),
            SourceAndDestination("M-KRSHNP", "M-JNKP") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-JNKP", "M-KRSHNP") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-JNKP", "M-DBR") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-DBR", "M-JNKP") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-DBR", "M-DSH") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-DSH", "M-DBR") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-DSH", "M-PLM") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-PLM", "M-DSH") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-PLM", "M-SDR") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-SDR", "M-PLM") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-SDR", "M-TRM") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-TRM", "M-SDR") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-TRM", "M-SHN") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-SHN", "M-TRM") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-SHN", "M-VSN") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-VSN", "M-SHN") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-VSN", "M-MNR") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-MNR", "M-VSN") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-MNR", "M-RKP") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-RKP", "M-MNR") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-RKP", "M-ITZ") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-ITZ", "M-RKP") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-ITZ", "M-HZK") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-HZK", "M-ITZ") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-HZK", "M-PNC") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-PNC", "M-HZK") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-PNC", "M-CHR") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-CHR", "M-PNC") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-CHR", "M-GRT") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-GRT", "M-CHR") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-GRT", "M-NHRN") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-NHRN", "M-GRT") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-NHRN", "M-KLK") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-KLK", "M-NHRN") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-KLK", "M-OKH") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-OKH", "M-KLK") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-OKH", "M-SKH") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-SKH", "M-OKH") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-SKH", "M-JMML") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-JMML", "M-SKH") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-JMML", "M-OKHL") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-OKHL", "M-JMML") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-OKHL", "M-JSLV") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-JSLV", "M-OKHL") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-JSLV", "M-KLN") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-KLN", "M-JSLV") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-KLN", "M-OKHLB") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-OKHLB", "M-KLN") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-OKHLB", "M-BTN") to listOf(LabelledGraphEdge("M1", 1)),
            SourceAndDestination("M-BTN", "M-OKHLB") to listOf(LabelledGraphEdge("M2", 1)),
            SourceAndDestination("M-DPT", "M-GNDF") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-GNDF", "M-DPT") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-GNDF", "M-DLT") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-DLT", "M-GNDF") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-DLT", "M-ALP") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-ALP", "M-DLT") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-ALP", "M-JYP") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-JYP", "M-ALP") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-JYP", "M-KNW") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-KNW", "M-JYP") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-KNW", "M-NDSCTR") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-NDSCTR", "M-KNW") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-NDSCTR", "M-SCTR1") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-SCTR1", "M-NDSCTR") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-SCTR1", "M-NDSCTR14") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-NDSCTR14", "M-SCTR1") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-NDSCTR14", "M-NDSCTR145") to listOf(
                LabelledGraphEdge(
                    "AQ1",
                    1
                )
            ),
            SourceAndDestination("M-NDSCTR145", "M-NDSCTR14") to listOf(
                LabelledGraphEdge(
                    "AQ2",
                    1
                )
            ),
            SourceAndDestination("M-NDSCTR145", "M-NDSCTR144") to listOf(
                LabelledGraphEdge(
                    "AQ1",
                    1
                )
            ),
            SourceAndDestination("M-NDSCTR144", "M-NDSCTR145") to listOf(
                LabelledGraphEdge(
                    "AQ2",
                    1
                )
            ),
            SourceAndDestination("M-NDSCTR144", "M-NDSCTR143") to listOf(
                LabelledGraphEdge(
                    "AQ1",
                    1
                )
            ),
            SourceAndDestination("M-NDSCTR143", "M-NDSCTR144") to listOf(
                LabelledGraphEdge(
                    "AQ2",
                    1
                )
            ),
            SourceAndDestination("M-NDSCTR143", "M-NDSCTR142") to listOf(
                LabelledGraphEdge(
                    "AQ1",
                    1
                )
            ),
            SourceAndDestination("M-NDSCTR142", "M-NDSCTR143") to listOf(
                LabelledGraphEdge(
                    "AQ2",
                    1
                )
            ),
            SourceAndDestination("M-NDSCTR142", "M-NDSCTR13") to listOf(
                LabelledGraphEdge(
                    "AQ1",
                    1
                )
            ),
            SourceAndDestination("M-NDSCTR13", "M-NDSCTR142") to listOf(
                LabelledGraphEdge(
                    "AQ2",
                    1
                )
            ),
            SourceAndDestination("M-NDSCTR13", "M-SCTR8") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-SCTR8", "M-NDSCTR13") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-SCTR8", "M-NSZ") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-NSZ", "M-SCTR8") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-NSZ", "M-NDSCTR81") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-NDSCTR81", "M-NSZ") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-NDSCTR81", "M-NDSCTR10") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-NDSCTR10", "M-NDSCTR81") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-NDSCTR10", "M-NDSCTR7") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-NDSCTR7", "M-NDSCTR10") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-NDSCTR7", "M-NDSCTR5") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-NDSCTR5", "M-NDSCTR7") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-NDSCTR5", "M-NDSCTR51") to listOf(LabelledGraphEdge("AQ1", 1)),
            SourceAndDestination("M-NDSCTR51", "M-NDSCTR5") to listOf(LabelledGraphEdge("AQ2", 1)),
            SourceAndDestination("M-SMY", "M-RHNSC") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-RHNSC", "M-SMY") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-RHNSC", "M-HDR") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-HDR", "M-RHNSC") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-HDR", "M-JGPI") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-JGPI", "M-HDR") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-JGPI", "M-ADR") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-ADR", "M-JGPI") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-ADR", "M-AZDP") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-AZDP", "M-ADR") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-AZDP", "M-MDL") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-MDL", "M-AZDP") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-MDL", "M-GTB") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-GTB", "M-MDL") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-GTB", "M-VSHW") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-VSHW", "M-GTB") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-VSHW", "M-VDH") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-VDH", "M-VSHW") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-VDH", "M-CVL") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-CVL", "M-VDH") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-CVL", "M-KSHM") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-KSHM", "M-CVL") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-KSHM", "M-CHN") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-CHN", "M-KSHM") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-CHN", "M-CHW") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-CHW", "M-CHN") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-CHW", "M-NWDLH") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-NWDLH", "M-CHW") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-NWDLH", "M-RJV") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-RJV", "M-NWDLH") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-RJV", "M-PTLC") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-PTLC", "M-RJV") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-PTLC", "M-CNTR") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-CNTR", "M-PTLC") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-CNTR", "M-UDYG") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-UDYG", "M-CNTR") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-UDYG", "M-LKK") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-LKK", "M-UDYG") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-LKK", "M-JRB") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-JRB", "M-LKK") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-JRB", "M-DLL") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-DLL", "M-JRB") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-DLL", "M-AMS") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-AMS", "M-DLL") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-AMS", "M-GRN") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-GRN", "M-AMS") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-GRN", "M-HZK") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-HZK", "M-GRN") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-HZK", "M-MVNR") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-MVNR", "M-HZK") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-MVNR", "M-SAKT") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-SAKT", "M-MVNR") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-SAKT", "M-QTB") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-QTB", "M-SAKT") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-QTB", "M-CHH") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-CHH", "M-QTB") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-CHH", "M-SLT") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-SLT", "M-CHH") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-SLT", "M-GHTR") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-GHTR", "M-SLT") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-GHTR", "M-ARJ") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-ARJ", "M-GHTR") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-ARJ", "M-GRD") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-GRD", "M-ARJ") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-GRD", "M-SKNDR") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-SKNDR", "M-GRD") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-SKNDR", "M-MGRD") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-MGRD", "M-SKNDR") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-MGRD", "M-IFF") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-IFF", "M-MGRD") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-IFF", "M-MLL") to listOf(LabelledGraphEdge("Y1", 1)),
            SourceAndDestination("M-MLL", "M-IFF") to listOf(LabelledGraphEdge("Y2", 1)),
            SourceAndDestination("M-NDSCTR51", "M-SCTR5") to listOf(LabelledGraphEdge("WA", 0)),
            SourceAndDestination("M-SCTR5", "M-NDSCTR51") to listOf(LabelledGraphEdge("WA", 0))

        )
    }

    override fun stationLines(): Map<String, List<String>> {
        return mapOf(
            "M-LXM" to listOf("Blue"),
            "M-NRM" to listOf("Blue"),
            "M-PTVR" to listOf("Blue"),
            "M-KRKRD" to listOf("Blue", "Pink"),
            "M-ANND" to listOf("Blue", "Pink"),
            "M-KSH" to listOf("Blue"),
            "M-VSH" to listOf("Blue"),
            "M-NDLC" to listOf("Blue"),
            "M-SCT" to listOf("Blue"),
            "M-SCTR" to listOf("Blue"),
            "M-SCTR6" to listOf("Blue"),
            "M-SCTR5" to listOf("Blue"),
            "M-SCTR3" to listOf("Blue"),
            "M-NCC" to listOf("Blue"),
            "M-GLF" to listOf("Blue"),
            "M-BTN" to listOf("Blue", "Magenta"),
            "M-NDS" to listOf("Blue"),
            "M-NDSC" to listOf("Blue"),
            "M-NDSCT" to listOf("Blue"),
            "M-NWS" to listOf("Blue"),
            "M-MYR" to listOf("Blue"),
            "M-MYRVHR" to listOf("Blue", "Pink"),
            "M-AKS" to listOf("Blue"),
            "M-YMN" to listOf("Blue"),
            "M-IND" to listOf("Blue"),
            "M-SPR" to listOf("Blue"),
            "M-MDHS" to listOf("Blue", "Violet"),
            "M-BRK" to listOf("Blue"),
            "M-RJV" to listOf("Blue", "Yellow"),
            "M-RKS" to listOf("Blue"),
            "M-JHN" to listOf("Blue"),
            "M-KB" to listOf("Blue"),
            "M-RJN" to listOf("Blue"),
            "M-PTL" to listOf("Blue"),
            "M-SHD" to listOf("Blue"),
            "M-KRT" to listOf("Blue", "Green"),
            "M-MTN" to listOf("Blue"),
            "M-RN" to listOf("Blue"),
            "M-RJRG" to listOf("Blue", "Pink"),
            "M-TGR" to listOf("Blue"),
            "M-SBH" to listOf("Blue"),
            "M-TLK" to listOf("Blue"),
            "M-JNK" to listOf("Blue"),
            "M-JNKP" to listOf("Blue", "Magenta"),
            "M-UTT" to listOf("Blue"),
            "M-UTTM" to listOf("Blue"),
            "M-NWD" to listOf("Blue"),
            "M-DWR" to listOf("Blue"),
            "M-DWRK" to listOf("Blue", "Grey"),
            "M-DWRKS" to listOf("Blue"),
            "M-DWRKSC" to listOf("Blue"),
            "M-DWRKSCT" to listOf("Blue"),
            "M-DWRKSCTR" to listOf("Blue"),
            "M-DWRKSCTR1" to listOf("Blue"),
            "M-DWRKSCTR9" to listOf("Blue"),
            "M-DWRKSCTR8" to listOf("Blue"),
            "M-DWRKSCTR2" to listOf("Blue", "Airport Express"),
            "M-MJPR" to listOf("Pink"),
            "M-JFR" to listOf("Pink"),
            "M-WLCM" to listOf("Pink", "Red"),
            "M-EST" to listOf("Pink"),
            "M-KRS" to listOf("Pink"),
            "M-KKDC" to listOf("Pink"),
            "M-IPE" to listOf("Pink"),
            "M-MNDW" to listOf("Pink"),
            "M-ESTV" to listOf("Pink"),
            "M-TRL" to listOf("Pink"),
            "M-MYRVH" to listOf("Pink"),
            "M-HZR" to listOf("Pink"),
            "M-ASH" to listOf("Pink"),
            "M-VNB" to listOf("Pink"),
            "M-LJPT" to listOf("Pink", "Violet"),
            "M-SOEN" to listOf("Pink"),
            "M-DLL" to listOf("Pink", "Yellow"),
            "M-SRJ" to listOf("Pink"),
            "M-BHK" to listOf("Pink"),
            "M-SRM" to listOf("Pink"),
            "M-DRG" to listOf("Pink"),
            "M-DLH" to listOf("Pink"),
            "M-NAVR" to listOf("Pink"),
            "M-MYP" to listOf("Pink"),
            "M-ESB" to listOf("Pink"),
            "M-PNJBBG" to listOf("Pink", "Green"),
            "M-SHK" to listOf("Pink"),
            "M-NTJ" to listOf("Pink", "Red"),
            "M-SHL" to listOf("Pink"),
            "M-AZDP" to listOf("Pink", "Yellow"),
            "M-MKPR" to listOf("Pink"),
            "M-SHV" to listOf("Pink"),
            "M-JIEE" to listOf("Pink"),
            "M-GKL" to listOf("Pink"),
            "M-S55" to listOf("Rapid Metro"),
            "M-SCTR54" to listOf("Rapid Metro"),
            "M-SCTR53" to listOf("Rapid Metro"),
            "M-SCTR4" to listOf("Rapid Metro"),
            "M-PHS" to listOf("Rapid Metro"),
            "M-SKNDR" to listOf("Rapid Metro", "Yellow"),
            "M-DL2" to listOf("Rapid Metro"),
            "M-BLV" to listOf("Rapid Metro"),
            "M-CYB" to listOf("Rapid Metro"),
            "M-MLS" to listOf("Rapid Metro"),
            "M-PHS3Z" to listOf("Rapid Metro"),
            "M-NNG" to listOf("Grey"),
            "M-NJF" to listOf("Grey"),
            "M-DHNS" to listOf("Grey"),
            "M-RTH" to listOf("Red"),
            "M-RHN" to listOf("Red"),
            "M-RHNS" to listOf("Red"),
            "M-PTP" to listOf("Red"),
            "M-KHT" to listOf("Red"),
            "M-KSHV" to listOf("Red"),
            "M-KNH" to listOf("Red"),
            "M-INDR" to listOf("Red", "Green"),
            "M-SHS" to listOf("Red"),
            "M-PRTP" to listOf("Red"),
            "M-PLB" to listOf("Red"),
            "M-TSH" to listOf("Red"),
            "M-KSHM" to listOf("Red", "Violet", "Yellow"),
            "M-SHST" to listOf("Red"),
            "M-SLM" to listOf("Red"),
            "M-SHH" to listOf("Red"),
            "M-MNS" to listOf("Red"),
            "M-JHL" to listOf("Red"),
            "M-DLS" to listOf("Red"),
            "M-SHHD" to listOf("Red"),
            "M-RJB" to listOf("Red"),
            "M-MJR" to listOf("Red"),
            "M-SHY" to listOf("Red"),
            "M-MHN" to listOf("Red"),
            "M-ART" to listOf("Red"),
            "M-HND" to listOf("Red"),
            "M-SHHDS" to listOf("Red"),
            "M-NWDLH" to listOf("Airport Express", "Yellow"),
            "M-SHVJ" to listOf("Airport Express"),
            "M-DHL" to listOf("Airport Express"),
            "M-DACY" to listOf("Airport Express"),
            "M-APOT" to listOf("Airport Express"),
            "M-IICCZ" to listOf("Airport Express"),
            "M-LLQ" to listOf("Violet"),
            "M-JAMD" to listOf("Violet"),
            "M-DLHG" to listOf("Violet"),
            "M-IT" to listOf("Violet"),
            "M-JNP" to listOf("Violet"),
            "M-CNTR" to listOf("Violet", "Yellow"),
            "M-KHN" to listOf("Violet"),
            "M-JLN" to listOf("Violet"),
            "M-JNG" to listOf("Violet"),
            "M-MLCD" to listOf("Violet"),
            "M-KHCY" to listOf("Violet"),
            "M-NHR" to listOf("Violet"),
            "M-KLK" to listOf("Violet", "Magenta"),
            "M-GVN" to listOf("Violet"),
            "M-HRK" to listOf("Violet"),
            "M-JSL" to listOf("Violet"),
            "M-SRT" to listOf("Violet"),
            "M-MHNS" to listOf("Violet"),
            "M-TGH" to listOf("Violet"),
            "M-BDR" to listOf("Violet"),
            "M-SR" to listOf("Violet"),
            "M-NHP" to listOf("Violet"),
            "M-MWL" to listOf("Violet"),
            "M-SCTR2" to listOf("Violet"),
            "M-BDK" to listOf("Violet"),
            "M-OLDF" to listOf("Violet"),
            "M-NCAJ" to listOf("Violet"),
            "M-BTC" to listOf("Violet"),
            "M-ESC" to listOf("Violet"),
            "M-SNT" to listOf("Violet"),
            "M-RJNH" to listOf("Violet"),
            "M-SRSM" to listOf("Green"),
            "M-ASHK" to listOf("Green"),
            "M-PNJB" to listOf("Green"),
            "M-SHVJP" to listOf("Green"),
            "M-MDP" to listOf("Green"),
            "M-PSC" to listOf("Green"),
            "M-PSCH" to listOf("Green"),
            "M-PRG" to listOf("Green"),
            "M-UDY" to listOf("Green"),
            "M-MHR" to listOf("Green"),
            "M-NNGL" to listOf("Green"),
            "M-NNGLR" to listOf("Green"),
            "M-RJD" to listOf("Green"),
            "M-MUDK" to listOf("Green"),
            "M-MNDKN" to listOf("Green"),
            "M-GHV" to listOf("Green"),
            "M-TKLM" to listOf("Green"),
            "M-TKRB" to listOf("Green"),
            "M-PNDT" to listOf("Green"),
            "M-BUSS" to listOf("Green"),
            "M-BRG" to listOf("Green"),
            "M-DBR" to listOf("Magenta"),
            "M-DSH" to listOf("Magenta"),
            "M-PLM" to listOf("Magenta"),
            "M-SDR" to listOf("Magenta"),
            "M-TRM" to listOf("Magenta"),
            "M-SHN" to listOf("Magenta"),
            "M-VSN" to listOf("Magenta"),
            "M-MNR" to listOf("Magenta"),
            "M-RKP" to listOf("Magenta"),
            "M-ITZ" to listOf("Magenta"),
            "M-HZK" to listOf("Magenta", "Yellow"),
            "M-PNC" to listOf("Magenta"),
            "M-CHR" to listOf("Magenta"),
            "M-GRT" to listOf("Magenta"),
            "M-NHRN" to listOf("Magenta"),
            "M-OKH" to listOf("Magenta"),
            "M-SKH" to listOf("Magenta"),
            "M-JMML" to listOf("Magenta"),
            "M-OKHL" to listOf("Magenta"),
            "M-JSLV" to listOf("Magenta"),
            "M-KLN" to listOf("Magenta"),
            "M-OKHLB" to listOf("Magenta"),
            "M-KRSHNP" to listOf("Magenta"),
            "M-DPT" to listOf("Aqua"),
            "M-GNDF" to listOf("Aqua"),
            "M-DLT" to listOf("Aqua"),
            "M-ALP" to listOf("Aqua"),
            "M-JYP" to listOf("Aqua"),
            "M-KNW" to listOf("Aqua"),
            "M-NDSCTR" to listOf("Aqua"),
            "M-SCTR1" to listOf("Aqua"),
            "M-NDSCTR14" to listOf("Aqua"),
            "M-NDSCTR145" to listOf("Aqua"),
            "M-NDSCTR144" to listOf("Aqua"),
            "M-NDSCTR143" to listOf("Aqua"),
            "M-NDSCTR142" to listOf("Aqua"),
            "M-NDSCTR13" to listOf("Aqua"),
            "M-SCTR8" to listOf("Aqua"),
            "M-NSZ" to listOf("Aqua"),
            "M-NDSCTR81" to listOf("Aqua"),
            "M-NDSCTR10" to listOf("Aqua"),
            "M-NDSCTR7" to listOf("Aqua"),
            "M-NDSCTR5" to listOf("Aqua"),
            "M-NDSCTR51" to listOf("Aqua"),
            "M-SMY" to listOf("Yellow"),
            "M-RHNSC" to listOf("Yellow"),
            "M-HDR" to listOf("Yellow"),
            "M-JGPI" to listOf("Yellow"),
            "M-ADR" to listOf("Yellow"),
            "M-MDL" to listOf("Yellow"),
            "M-GTB" to listOf("Yellow"),
            "M-VSHW" to listOf("Yellow"),
            "M-VDH" to listOf("Yellow"),
            "M-CVL" to listOf("Yellow"),
            "M-CHN" to listOf("Yellow"),
            "M-CHW" to listOf("Yellow"),
            "M-PTLC" to listOf("Yellow"),
            "M-UDYG" to listOf("Yellow"),
            "M-LKK" to listOf("Yellow"),
            "M-JRB" to listOf("Yellow"),
            "M-AMS" to listOf("Yellow"),
            "M-GRN" to listOf("Yellow"),
            "M-MVNR" to listOf("Yellow"),
            "M-SAKT" to listOf("Yellow"),
            "M-QTB" to listOf("Yellow"),
            "M-CHH" to listOf("Yellow"),
            "M-SLT" to listOf("Yellow"),
            "M-GHTR" to listOf("Yellow"),
            "M-ARJ" to listOf("Yellow"),
            "M-GRD" to listOf("Yellow"),
            "M-MGRD" to listOf("Yellow"),
            "M-IFF" to listOf("Yellow"),
            "M-MLL" to listOf("Yellow")
        )
    }

    override val cityName: String
        get() = City.Delhi.name

    override fun aliasGroups(): Map<String, List<String>> = mapOf(
        "M-NDSCTR51" to listOf("M-SCTR5"),
        "M-SCTR5" to listOf("M-NDSCTR51")
    )

}